#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_GALILEO)     += lps22hb/
obj-$(CONFIG_PULSE)     += lps22hb/
obj-$(CONFIG_RENAISSANCE)     += lps22hb/
obj-$(CONFIG_NOBLESSE)     += lps22hb_noblesse/
