obj-$(CONFIG_EXYNOS_MIPI_DSIM) += common.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA2K)	+= s6e3ha2k_mipi_lcd.o s6e3ha2k_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF4)	+= s6e3hf4_mipi_lcd.o s6e3hf4_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA6)	+= s6e3ha6_mipi_lcd.o s6e3ha6_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA8)	+= s6e3ha8_mipi_lcd.o s6e3ha8_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3AA2)	+= s6e3aa2_mipi_lcd.o s6e3aa2_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W2X01)  += s6e36w2x01_mipi_lcd.o s6e36w2x01_lcd_ctrl.o s6e36w2x01_dimming.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W3X01_L)  += s6e36w3x01_l_mipi_lcd.o s6e36w3x01_l_lcd_ctrl.o s6e36w3x01_l_dimming.o s6e36w3x01_sc_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W3X01_S)  += s6e36w3x01_s_mipi_lcd.o s6e36w3x01_s_lcd_ctrl.o s6e36w3x01_s_dimming.o s6e36w3x01_sc_ctrl.o
ifdef CONFIG_NOBLESSE
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W4X01_L)  += s6e36w4x01_mipi_lcd.o s6e36w4x01_lcd_ctrl_noblesse.o s6e36w4x01_l_dimming_noblesse.o s6e36w4x01_sc_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W4X01_S)  += s6e36w4x01_mipi_lcd.o s6e36w4x01_lcd_ctrl_noblesse.o s6e36w4x01_s_dimming_noblesse.o s6e36w4x01_sc_ctrl.o
else
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W4X01_L)  += s6e36w4x01_mipi_lcd.o s6e36w4x01_lcd_ctrl_renaissance.o s6e36w4x01_l_dimming_renaissance.o s6e36w4x01_sc_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E36W4X01_S)  += s6e36w4x01_mipi_lcd.o s6e36w4x01_lcd_ctrl_renaissance.o s6e36w4x01_s_dimming_renaissance.o s6e36w4x01_sc_ctrl.o
endif
obj-$(CONFIG_EXYNOS_DECON_LCD_RM6D010)  += rm6d010_mipi_lcd.o rm6d010_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_RM69330)  += rm69330_mipi_lcd.o rm69330_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_RM69091)  += rm69091_mipi_lcd.o rm69091_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_EMUL_DISP) += emul_disp_mipi_lcd.o emul_disp_lcd_ctrl.o
